mysql_host: localhost
mysql_root_password: root

drupal_version: 7.8
drupal_site_name: REAN Cloud Technical Assessment Site
drupal_admin_username: admin
drupal_admin_password: admin
drupal_db_name: drupaldb
drupal_table_prefix: drupal_

drush_version: 7.x-4.5
